### ISSUE TITLE
MUSAN for close condition of ASVspoof5 Track 2 SASV Challenge

### ISSUE THREAD

**Issue by zlin0** [sasv-challenge/SASV2_Baseline#5]
Hi @Jungjee Jee-weon, thanks for providing the baseline for ASVspoof5 Track 2 SASV!

I noticed that you included MUSAN in your code for augmentation, but I am unsure if it (or which subset) is allowed in the closed condition of the challenge. Sorry for bothering you on GitHub, but there isn't much information about using MUSAN for close conditions in the evaluation plan. `For the closed condition, the use of external non-speech and non-voice resources (e.g. noise samples and impulse responses), speech codecs and audio compression tools for training or data augmentation IS permitted, under the condition that their use is detailed in the system description accompanying any submission`
Based on both eval. plan and email to asvspoof5@lists.asvspoof.org, it appears that only MUSAN noise can be used for augmentation. Is this correct? Or did I miss any information?

Thanks!

**Comment by Jungjee** [comment]
Hi @zlin0, you are correct. Musan babble cannot be utilized. I will update the codebase to adapt for this regulation.
Thank you for pointing this out!

**Comment by zlin0** [comment]
Thanks!
